"""бреад

Revision ID: ef1af663f4a5
Revises: b4bae974c4c9
Create Date: 2023-04-16 16:35:30.640983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef1af663f4a5'
down_revision = 'b4bae974c4c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
